### ISSUE TITLE
404 error when building in corber to android

### ISSUE THREAD

**Issue by wallacyalva** [kaermorchen/ember-mdi#2]
![image](https://user-images.githubusercontent.com/38988660/56362336-f8a93f80-61bf-11e9-810f-fdbf6456e613.png)
I am trying to use these icon in ember but when I give build through the corber it returns me these errors of not found. follows error print

**Comment by kaermorchen** [comment]
Hi.

I didn't use corber and don't understand how it works. 

Do your project have a rootURL? Maybe you should use `prepend` in the `fingerprint` option.

Or you can override `mdi-icon` [template](https://github.com/kaermorchen/ember-mdi/blob/master/addon/templates/components/mdi-icon.hbs) and user a right path to icons.svg
